### ISSUE TITLE
[FEATURE] 카드 삭제 기능 구현

### ISSUE THREAD

**Issue by KimKwon** [woowa-techcamp-2022/web-todo-9#25]
## 🌴 작업 브랜치 

`feat/card-delete`

## 💼 TASK 개요 

카드 삭제 기능을 구현해요.
관련한 호버, 클릭 이벤트도 핸들링할 예정이에요.

## ✅ TODO 및 진행현황 

- [x] 삭제
  - [x] X 버튼에 대해 클릭 이벤트를 적용해요. 
  - [x] 카드의 호버 이벤트를 핸들링해요.
  - [x] 삭제 API를 구현해요.

모달은 다른 브랜치에서 작업하겠습니다.
우선 X버튼 누르면 바로 삭제되는 것을 목표로 할게요 ! 

## ⏰ 예상 소요 시간 

2h 정도 예상합니다
